#! /bin/bash

# this script is meant to be run by yadm, assumes yay is already installed on the system
# portions of this script have been adapted from Luke Smith's LARBS:
# https://github.com/LukeSmithxyz/LARBS

set -e

# elevate sudo as needed
# [ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

base_packages=(
    "alsa-utils"
    "arc-gtk-theme"
    "bat"
    "bspwm"
    "code"
    "curl"
    "dunst"
    "emacs"
    "exa"
    "feh"
    "firefox-developer-edition"
    "fzf"
    "gvfs-smb"
    "gimp"
    "highlight"
    "htop"
    "ipython"
    "libreoffice-fresh"
    "maim"
    "mpd"
    "mpv"
    "ncmpcpp"
    "nemo"
    "neofetch"
    "neovim"
    "network-manager-applet"
    "nodejs"
    "npm"
    "nvidia"
    "ntfs-3g"
    "openssh"
    "peek"
    "postgresql"
    "python-pip"
    "python-pipenv"
    "python-virtualenvwrapper"
    "ranger"
    "ripgrep"
    "rofi"
    "samba"
    "smplayer"
    "smplayer-skins"
    "smplayer-themes"
    "sxhkd"
    "sxiv"
    "tidy"
    "tmux"
    "transmission-gtk"
    "ttf-freefont"
    "ttf-hack"
    "vifm"
    "vlc"
    "x11-ssh-askpass"
    "xcape"
    "xorg-xbacklight"
    "xorg-xsetroot"
    "yarn"
    "youtube-dl"
    "zathura"
    "zathura-pdf-poppler"
    "zsh"
)

aur_packages=(
    "betterlockscreen"
    "compton-tryone-git"
    "dragon-drag-and-drop-git"
    "gitflow-avh"
    "google-chrome"
    "gotop-bin"
    "mongodb-bin"
    "nerd-fonts-fira-code"
    "nerd-fonts-ubuntu-mono"
    "noto-fonts-emoji"
    "numix-icon-theme-git"
    "polybar"
    "rar"
    "stellar"
    "subliminal"
    "tdrop-git"
    "ttf-clear-sans"
    "ttf-font-awesome-4"
    "ttf-ubuntu-font-family"
    "vivaldi"
    "xst"
)

echo "## Installing Base Packages..."
yay -S --noconfirm --needed ${base_packages[@]}

echo "## Installing AUR Packages..."
yay -S --noconfirm --needed ${aur_packages[@]}

# Make pacman and yay colorful and adds eye candy on the progress bar because why not.
grep "^Color" /etc/pacman.conf >/dev/null || sudo sed -i "s/^#Color/Color/" /etc/pacman.conf
grep "ILoveCandy" /etc/pacman.conf >/dev/null || sudo sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Bootstrapping oh-my-zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi


# declare ZSH_CUSTOM as it isnt defined in bash
ZSH_CUSTOM=~/.oh-my-zsh/custom
if [ ! -d "$ZSH_CUSTOM/themes/spaceship-prompt" ]; then
    echo "Bootstrapping spaceship-prompt..."
    git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
    ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
fi

if command -v nvim >/dev/null 2>&1; then
    echo "Bootstrapping Vim..."
    nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

# Autologin
# if [ ! -d "/etc/systemd/system/getty@tty1.service.d/override.conf" ]; then
#     echo "Setting up auto login..."
#     sudo mkdir -p /etc/systemd/system/getty@tty1.service.d

#     echo "[Service]" > tee /etc/systemd/system/getty@tty1.service.d/override.conf
#     echo "ExecStart=-/usr/bin/agetty --autologin username --noclear %I $TERM" >> tee -a /etc/systemd/system/getty@tty1.service.d/override.conf
# fi

# TODO: bootstrap emacs, vscode?
# TODO: reminder about .ssh folder
