#!/bin/sh

# termclass="St"
termclass="st-256color"
browserclass="Google-chrome-unstable"

webworkspace=1
fileworkspace=3
sectermworkspace=7
listworkspace=8
chatworkspace=9
dlworkspace=10

# set wallpaper
if xrandr | grep "eDP1 connected"; then
    feh --no-fehbg --bg-fill '/home/iynaix/Pictures/Wallpapers/wallhaven-659622_1920.png'
else
    feh --no-fehbg --bg-fill '/home/iynaix/Pictures/Wallpapers/wallhaven-659622_3440.png' '/home/iynaix/Pictures/Wallpapers/wallhaven-659622_2560.png'
fi

# start compton
compton -b &

# TODO: receptacles on web and downloads workspaces

# web browsers
bspc rule -a $browserclass -o desktop=$webworkspace follow=on &
google-chrome-unstable --incognito &

bspc rule -a $browserclass -o desktop=$webworkspace &
google-chrome-unstable &

# workflowy
bspc rule -a WorkFlowy -o desktop=$listworkspace &
env DESKTOPINTEGRATION=0 /opt/WorkFlowy-x86_64.AppImage &

# downloads workspace
if ! xrandr | grep -q "eDP1 connected"; then
    transmission-gtk &
fi

bspc rule -a $termclass:dltxt -o desktop=$dlworkspace &
$TERMINAL -n dltxt -e nvim ~/Desktop/yt.txt &

bspc rule -a $termclass:dlterm -o desktop=$dlworkspace &
$TERMINAL -n dlterm &

# chatworkspace
# google-chrome-unstable --app=https://web.whatsapp.com &

# terminal workspaces
bspc rule -a $termclass:ranger -o desktop=$fileworkspace &
$TERMINAL -n ranger -e ranger ~/Downloads &

bspc rule -a $termclass:initialterm -o desktop=$sectermworkspace follow=on &
$TERMINAL -n initialterm &
