#!/bin/sh

# termclass="St"
termclass="xst-256color"
chromeclass="Brave-browser"

webdesktop=1
filedesktop=3
nemodesktop=4
sectermdesktop=7
listdesktop=8
chatdesktop=9
dldesktop=10

# setups for different machines
if xrandr | grep "eDP1 connected"; then
    xwallpaper --output 'eDP1' --zoom '/home/iynaix/Pictures/Wallpapers/balloons_1920.png'

    # remap caps lock to mod tap Esc and Super
    xmodmap ~/.xmodmap
    xcape -e 'Super_R=Escape' -t 200
else
    xwallpaper --output 'DP-2' --zoom '/home/iynaix/Pictures/Wallpapers/balloons_3440.png' --output 'DP-0.8' --zoom '/home/iynaix/Pictures/Wallpapers/balloons_2560.png'
fi

# (re)start picom
pgrep picom && pkill picom || picom -b --experimental-backends &

# TODO: receptacles on web and downloads desktops

# web browsers
bspc rule -a $chromeclass -o desktop=$webdesktop follow=on &
brave --incognito &

bspc rule -a $chromeclass -o desktop=$webdesktop &
brave &

# downloads desktop
if ! xrandr | grep -q "eDP1 connected"; then
    transmission-gtk &
fi

bspc rule -a $termclass:dltxt -o desktop=$dldesktop &
$TERMINAL -n dltxt -e nvim ~/Desktop/yt.txt &

bspc rule -a $termclass:dlterm -o desktop=$dldesktop &
$TERMINAL -n dlterm &

# nemo desktop
bspc rule -a Nemo:nemo -o desktop=$nemodesktop &
nemo &

# chat desktop
firefox-developer-edition --class=ffchat https://discordapp.com/channels/@me https://web.whatsapp.com &

# terminal desktops
bspc rule -a $termclass:ranger -o desktop=$filedesktop &
$TERMINAL -n ranger -e ranger ~/Downloads &

bspc rule -a $termclass:initialterm -o desktop=$sectermdesktop follow=on &
$TERMINAL -n initialterm &

# subscribe to bspc events
# note: this must be the last line in the file!
bspc subscribe all | bspc-events
