#! /bin/sh

if xrandr | grep "eDP1 connected"; then
    # laptop specific setup
    xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output HDMI1 --off --output VIRTUAL1 --off

    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10

    window_gap=8
    padding=8
else
    # desktop specific setup
    xrandr --output DP-0.8 --mode 2560x1440 --pos 0x0 --rotate left --output DVI-D-0 --off --output HDMI-0 --off --output DP-0 --off --output DP-1 --off --output DP-2 --primary --mode 3440x1440 --pos 1440x258 --rotate normal --output DP-3 --off --output DP-4 --off --output DP-5 --off

    bspc monitor %DP-0.8 -d 6 7 8 9 10
    bspc monitor DP-2 -d 1 2 3 4 5

    window_gap=15
    padding=15
fi

bspc config automatic_scheme longest_side

normal="#30302f"
focused="#4491ed"
bar_height=30
border_width=2

# borders and gaps
bspc config border_width         2
bspc config active_border_color  $normal
bspc config normal_border_color  $normal
bspc config focused_border_color $focused
bspc config window_gap           $window_gap
bspc config top_padding          $(( padding + bar_height ))
bspc config left_padding         $padding
bspc config right_padding        $padding
bspc config bottom_padding       $padding

bspc config presel_feedback_color   $focused
bspc config split_ratio             0.5
bspc config focus_follows_pointer   true
# smart gaps
bspc config single_monocle          true
bspc config borderless_monocle      false
bspc config gapless_monocle         true

# handle the mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a Code desktop=2 follow=on
bspc rule -a whatsapp desktop=9
bspc rule -a discord desktop=9 follow=on
bspc rule -a Filezilla desktop=10
bspc rule -a Transmission-gtk desktop=10
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating

[[ ! $(pidof -x sxhkd) ]] && sxhkd &
xrdb ~/.Xresources

# set the pointer
xsetroot -cursor_name left_ptr &

# polybar
~/.config/polybar/launch.sh &

# mpd
[ ! -s ~/.config/mpd/pid ] && mpd

[[ ! $(pidof -x chrome) ]] && ~/.config/bspwm/bspwm_start &
