#! /bin/sh

xrandr --output DP-0.8 --mode 2560x1440 --pos 0x0 --rotate left --output DVI-D-0 --off --output HDMI-0 --off --output DP-0 --off --output DP-1 --off --output DP-2 --primary --mode 3440x1440 --pos 1440x258 --rotate normal --output DP-3 --off --output DP-4 --off --output DP-5 --off

# bspc monitor -d 1 2 3 4 5 6 7 8 9 0
pri_wksp="1 2 3 4 5"
sec_wksp="6 7 8 9 10"

if xrandr | grep "eDP1 connected"; then
    bspc monitor DP-2 -d "$pri_wksp $sec_wksp"
else
    bspc monitor DP-2 -d $pri_wksp
    bspc monitor %DP-0.8 -d $sec_wksp
fi

bspc config automatic_scheme longest_side

active=#676e7d
focused=#f3f4f5
bar_height=30
padding=15
border_width=2

# borders and gaps
bspc config border_width         0
bspc config active_border_color  $active
bspc config focused_border_color $focused
bspc config window_gap           10
bspc config top_padding          $(( padding + bar_height ))
bspc config left_padding         $padding
bspc config right_padding        $padding
bspc config bottom_padding       $padding

bspc config presel_feedback_color   $active
bspc config split_ratio             0.5
bspc config focus_folows_pointer    true
# smart gaps
# bspc config single_monocle      true
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# handle the mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a discord desktop=9 follow=on
bspc rule -a Code desktop=2 follow=on
bspc rule -a Filezilla desktop=10

[[ ! $(pidof -x sxhkd) ]] && sxhkd &
~/.fehbg &
xrdb ~/.Xresources

[[ ! $(pidof -x sxhkd) ]] && sxhkd &
[[ ! $(pidof -x chrome) ]] && ~/.config/bspwm/bspwm_start &

# compton -b &
~/.config/polybar/launch.sh &
